# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "071ef4bc2d5212a037de6b3e7814363c"
name = "ambaril"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customers,read_discounts,read_draft_orders,read_fulfillments,read_inventory,read_locations,read_orders,read_price_rules,read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
