export { db, txDb } from "./client";
export type { Database, TxDatabase } from "./client";
export * as globalSchema from "./schema/global";
export * as checkoutSchema from "./schema/checkout";
export * as crmSchema from "./schema/crm";
export * as erpSchema from "./schema/erp";
export * as messagingSchema from "./schema/messaging";
export * as dashboardSchema from "./schema/dashboard";
export * as marketingSchema from "./schema/marketing";
export * as creatorsSchema from "./schema/creators";
